### ISSUE TITLE
When updating volto-button-block from 2.3.1 to 3.0.0 my project won't start because it cannot find volto-light-theme

### ISSUE THREAD

**Issue by fredvd** [kitconcept/volto-button-block#22]
I have a volto project with volto18alpha43 and volto-light-theme that I want to update to volta alpha18a46. 

While updating I noticed there is also a new release of volto-light-theme and that my pinned version of volto-button-block in the frontend-project add'on was still 2.3.1 instead of 3.0.X. (3.0.2 got pinned in volto-light-theme 5.0.1 last week). 

-----
When I update to any volto-button-block version 3.0.0 or 3.0.2 from 2.3.1,  and nothing else ( I even reverted the volto18 a43/a46 update).  I see the following backtrace that complain about an invalid razzle.config.js. And it is missing volto-light-theme.  volto-button-block is mentionned nowhere in the output. 

```
 ERROR  Invalid razzle.config.js file.

Error: Cannot find module '@kitconcept/volto-light-theme'
Require stack:
- /Users/fred/vmm/hoofdsite-project/frontend/node_modules/@plone/registry/src/addon-registry.js
- /Users/fred/vmm/hoofdsite-project/frontend/node_modules/@plone/volto/razzle.config.js
- /Users/fred/vmm/hoofdsite-project/frontend/razzle.config.js
- /Users/fred/vmm/hoofdsite-project/frontend/node_modules/razzle/config/loadRazzleConfig.js
- /Users/fred/vmm/hoofdsite-project/frontend/node_modules/razzle/scripts/start.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at AddonConfigurationRegistry.initPublishedPackage (/Users/fred/vmm/hoofdsite-project/frontend/node_modules/@plone/registry/src/addon-registry.js:255:32)
    at Array.forEach (<anonymous>)
    at AddonConfigurationRegistry.initPublishedPackages (/Users/fred/vmm/hoofdsite-project/frontend/node_modules/@plone/registry/src/addon-registry.js:243:21)
    at new AddonConfigurationRegistry (/Users/fred/vmm/hoofdsite-project/frontend/node_modules/@plone/registry/src/addon-registry.js:144:10)
    at Object.<anonymous> (/Users/fred/vmm/hoofdsite-project/frontend/node_modules/@plone/volto/razzle.config.js:27:18)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/fred/vmm/hoofdsite-project/frontend/razzle.config.js:22:34)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/fred/vmm/hoofdsite-project/frontend/node_modules/@plone/registry/src/addon-registry.js',
    '/Users/fred/vmm/hoofdsite-project/frontend/node_modules/@plone/volto/razzle.config.js',
    '/Users/fred/vmm/hoofdsite-project/frontend/razzle.config.js',
    '/Users/fred/vmm/hoofdsite-project/frontend/node_modules/razzle/config/loadRazzleConfig.js',
    '/Users/fred/vmm/hoofdsite-project/frontend/node_modules/razzle/scripts/start.js'
  ]
}
make: *** [start]
```
